Add close order reference on frontend
boomerdigital/solidus_amazon_payments pull request #40
Opened 2016-09-22 16:22 UTC by acreilly

- Add column closed_at to Spree::AmazonTransaction
- Add close action to  Spree::AmazonTransaction
- Add Spree::Payment::Processing#close! method
- Refactored SpreeAmazon::Order#close_order_reference! to respond with ActiveMerchant::Billing::Response
- Add amazon_payment to factories

2016-09-23 19:00 UTC, manmartinez commented on app/models/spree/amazon_transaction.rb
> +      return true if !can_close?(payment)
Here it's also better to use `unless` instead of `if !`

2016-09-23 19:02 UTC, manmartinez commented on spec/models/spree/payment/processing_decorator_spec.rb
> +  describe '#close!' do
I think this spec should just assert that the `close!` the source receives a call to `close!` no?

2016-09-23 19:02 UTC, manmartinez requested changes

2016-09-23 19:02 UTC, manmartinez commented on app/models/spree/payment/processing_decorator.rb
> +    return true if !source.respond_to?(:close!)
Probably change this to `return true unless source.respond_to?(:close!)`

2016-09-26 19:29 UTC, manmartinez commented on spec/models/spree/payment/processing_decorator_spec.rb
> +      expect(payment).to receive(:close!)
Sorry I think there's some confusion here, I meant something like this:

```ruby
it "delegates close! to the payment source" do 
  payment = create(:amazon_payment, state: 'completed')

  payment.close!

  expect(payment.source).to have_received(:close!)
end
```

2016-09-26 19:29 UTC, manmartinez requested changes

2016-09-27 18:56 UTC, acreilly commented on spec/models/spree/payment/processing_decorator_spec.rb
> +      expect(payment).to receive(:close!)
When I do this I get:

`1) Spree::Payment::Processing#close! delegates close! to the payment source
     Failure/Error: client.close_order_reference(@amazon_order_reference_id)

     WebMock::NetConnectNotAllowedError:
       Real HTTP connections are disabled. Unregistered request: POST https://mws.amazonservices.com/OffAmazonPayments_Sandbox/2013-01-01 with body 'AWSAccessKeyId=&Action=CloseOrderReference&AmazonOrderReferenceId=ORDER_REFERENCE&SellerId=&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2016-09-27T18%3A56%3A12Z&Version=2013-01-01&Signature=rTTOuhl2xyp4zmDEwCRacq58I08V26kbRTR%2FxBMucyA%3D' with headers {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Language=Ruby; ApplicationLibraryVersion=1.1.0; Platform=x86_64-darwin14; MWSClientVersion=2013-01-01; ApplicationName=; ApplicationVersion='}

       You can stub this request with the following snippet:

       stub_request(:post, "https://mws.amazonservices.com/OffAmazonPayments_Sandbox/2013-01-01").
         with(:body => "AWSAccessKeyId=&Action=CloseOrderReference&AmazonOrderReferenceId=ORDER_REFERENCE&SellerId=&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2016-09-27T18%3A56%3A12Z&Version=2013-01-01&Signature=rTTOuhl2xyp4zmDEwCRacq58I08V26kbRTR%2FxBMucyA%3D",
              :headers => {'Accept'=>'*/*', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'User-Agent'=>'Language=Ruby; ApplicationLibraryVersion=1.1.0; Platform=x86_64-darwin14; MWSClientVersion=2013-01-01; ApplicationName=; ApplicationVersion='}).
         to_return(:status => 200, :body => "", :headers => {})

       ============================================================
     # /Users/allisonreilly/.rvm/gems/ruby-2.2.1/gems/webmock-2.1.0/lib/webmock/http_lib_adapters/net_http.rb:114:in `request'
     # /Users/allisonreilly/.rvm/gems/ruby-2.2.1/gems/pay_with_amazon-1.1.0/lib/pay_with_amazon/request.rb:82:in `post'
     # /Users/allisonreilly/.rvm/gems/ruby-2.2.1/gems/pay_with_amazon-1.1.0/lib/pay_with_amazon/request.rb:48:in `send_post'
     # /Users/allisonreilly/.rvm/gems/ruby-2.2.1/gems/pay_with_amazon-1.1.0/lib/pay_with_amazon/client.rb:870:in `operation'
     # /Users/allisonreilly/.rvm/gems/ruby-2.2.1/gems/pay_with_amazon-1.1.0/lib/pay_with_amazon/client.rb:735:in `close_order_reference'
     # ./lib/amazon_mws.rb:142:in `close_order_reference'
     # ./app/models/spree_amazon/order.rb:25:in `close_order_reference!'
     # ./app/models/spree/amazon_transaction.rb:71:in `close!'
     # ./app/models/spree/payment/processing_decorator.rb:6:in `close!'
     # ./spec/models/spree/payment/processing_decorator_spec.rb:32:in `block (3 levels) in <top (required)>'`

2016-09-27 18:57 UTC, acreilly commented on spec/models/spree/payment/processing_decorator_spec.rb
> +      expect(payment).to receive(:close!)
When I stub the close request I get:

`
1) Spree::Payment::Processing#close! delegates close! to the payment source
     Failure/Error: expect(payment.source).to have_received(:close!)
       #<Spree::AmazonTransaction id: 1, order_id: nil, order_reference: "ORDER_REFERENCE", authorization_id: "AUTHORIZATION_ID", capture_id: "CAPTURE_ID", closed_at: "2016-09-27 18:57:27"> expected to have received close!, but that object is not a spy or method has not been stubbed.
     # ./spec/models/spree/payment/processing_decorator_spec.rb:35:in `block (3 levels) in <top (required)>'
`

2016-09-27 18:59 UTC, acreilly commented on spec/models/spree/payment/processing_decorator_spec.rb
> +      expect(payment).to receive(:close!)
When I do this it passes:

`
it 'delegates close! to the payment source' do
      payment = create(:amazon_payment, state: 'completed')
      allow_any_instance_of(Spree::AmazonTransaction).to receive(:close!)

      payment.close!

      expect(payment.source).to have_received(:close!)
    end
`

Any suggestions on a different approach?

2016-10-14 18:00 UTC, mtomov reviewed
Yeah, very clean code! 

I think it's just that test that Manuel has commented on to refactor .. else looks really good!

2016-10-14 18:00 UTC, mtomov commented on spec/models/spree/amazon_transaction_spec.rb
> +    end
You are becoming an expert with Webmock : )

2016-10-14 18:00 UTC, mtomov commented on app/models/spree/amazon_transaction.rb
>  end
That's some very clean easy to read code here!

2016-10-14 18:00 UTC, mtomov commented on spec/models/spree/amazon_transaction_spec.rb
> +    end
Can this not be just `be true` / `be false` ?

2016-10-14 18:00 UTC, mtomov commented on spec/models/spree/payment/processing_decorator_spec.rb
> +  describe '#close!' do
absolutely that ^ 

Avoid repetition in specs, as they become a burden later if the code changes in one place, and you have to change 10 tests for that. Should be just 1..

2016-10-14 18:00 UTC, mtomov commented on spec/models/spree/payment/processing_decorator_spec.rb
> +      expect(payment).to receive(:close!)
Yeah, you need to do it the other way around - stub it before it comes to it:

```ruby
expect(payment.source).to receive(:close!)
payment.close!
```

and that's it

2016-10-14 19:16 UTC, merged